### PR TITLE
feat(dev): nix support

### PR DESCRIPTION
**Pull request by willruggiano**
## What kind of change does this PR introduce?

Feature, for developers.

## What is the current behavior?

Nix(OS) developers need to globally install all tools.

## What is the new behavior?

Provide a project-specific "dev shell" for Nix(OS) developers.

## Additional context

N/A

### CODE REVIEW

**Comment by willruggiano** [comment]
Not sure how you guys feel about distro-specific configuration in your repository. If you'd rather, I can move the new nix files to a contrib/ directory.

**Comment by steve-chavez** [comment]
@willruggiano Could you guide me on what are the commands for trying this PR? I use Nix but I'm new to LSP.

Ideally something like:

```
$ nix-shell # download all deps
$ pglsp-start # start the lsp server
```

**Comment by willruggiano** [comment]
This doesn't really have anything to do with running the server within neovim. See the project's README for instructions on how to configure it with various editors.

**Comment by psteinroe** [comment]
hey @willruggiano, thanks for opening the pr. unfortunately, I am not experienced with nix and cannot maintain it. I am going to close this pr, maybe we can take another look at a later stage.

**Pull request closed without merging**
